#/bin/bash

# delete all __init__.py files as they are not required since Odoo 11.0
find . -name '__init__.py' | xargs rm -rf

cd setup

echo "# requirements.txt file generated by ${BUILD_DISPLAY_NAME}" > requirements.txt

for f in ./*; do
    echo 'Deploy module' $f
    if [ -d $f ]; then
        cd $f
        echo 'Deploy module' $f
<<<<<<< HEAD
        python setup.py sdist upload -r pypi-dev
        NAME="$(python setup.py --name)"
        VERSION="$(python setup.py --version)"
        echo "${NAME}=${VERSION}" >> ../requirements.txt
=======
        python setup.py sdist upload -r pypi-server
>>>>>>> 7cffae56d20ed645bbd7d49bdcc3218131d4caf6
        cd ..
    fi
done
